spring.application.name=order-service

# MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/order_service
spring.datasource.username=root
spring.datasource.password=Anto$2026
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8081

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1