spring.application.name=inventory-service


# MariaDB connection
spring.datasource.url=jdbc:mariadb://localhost:3306/inverntory
spring.datasource.username=root
spring.datasource.password=Anto$2026

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MariaDB driver
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver


# Server
server.port=0


# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Register using IP instead of Windows hostname
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1