spring.application.name=api-gateways

# =========================
# Eureka
# =========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


# =========================
# Logging
# =========================
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=DEBUG
logging.level.org.springframework.cloud.gateway=TRACE


# =========================
# Product Service
# =========================
spring.cloud.gateway.server.webflux.routes[0].id=product-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://product-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/products/**


# =========================
# Order Service
# =========================
spring.cloud.gateway.server.webflux.routes[1].id=order-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/order/**


# =========================
# Inventory Service
# =========================
spring.cloud.gateway.server.webflux.routes[2].id=inventory-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://inventory-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/inventory/**